export const EIGENLP_ABI = [
  {
    type: 'function',
    name: 'POOL_FEE',
    inputs: [],
    outputs: [{ name: '', type: 'uint24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'TICK_LOWER',
    inputs: [],
    outputs: [{ name: '', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'TICK_SPACING',
    inputs: [],
    outputs: [{ name: '', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'TICK_UPPER',
    inputs: [],
    outputs: [{ name: '', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'collectFees',
    inputs: [{ name: 'eigenId', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'compoundFees',
    inputs: [{ name: 'eigenId', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setAutoCompound',
    inputs: [
      { name: 'eigenId', type: 'bytes32' },
      { name: 'enabled', type: 'bool' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'autoCompoundEnabled',
    inputs: [{ name: 'eigenId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'eigenVault',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'seedPoolConcentrated',
    inputs: [
      { name: 'eigenId', type: 'bytes32' },
      { name: 'token', type: 'address' },
      { name: 'sqrtPriceX96', type: 'uint160' },
      { name: 'tokenAmount', type: 'uint256' },
      { name: 'tickLower', type: 'int24' },
      { name: 'tickUpper', type: 'int24' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'getPosition',
    inputs: [{ name: 'eigenId', type: 'bytes32' }],
    outputs: [
      { name: 'tokenId', type: 'uint256' },
      { name: 'poolId', type: 'bytes32' },
      { name: 'token', type: 'address' },
      { name: 'eigenOwner', type: 'address' },
      { name: 'fee', type: 'uint24' },
      { name: 'tickSpacing', type: 'int24' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'poolManager',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'positionManager',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'removeLiquidity',
    inputs: [
      { name: 'eigenId', type: 'bytes32' },
      { name: 'amount0Min', type: 'uint128' },
      { name: 'amount1Min', type: 'uint128' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'seedPool',
    inputs: [
      { name: 'eigenId', type: 'bytes32' },
      { name: 'token', type: 'address' },
      { name: 'sqrtPriceX96', type: 'uint160' },
      { name: 'tokenAmount', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'setOwner',
    inputs: [{ name: '_owner', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'approvedBundler',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setApprovedBundler',
    inputs: [{ name: '_bundler', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'seedPoolFor',
    inputs: [
      { name: 'eigenId', type: 'bytes32' },
      { name: 'token', type: 'address' },
      { name: 'sqrtPriceX96', type: 'uint160' },
      { name: 'tokenAmount', type: 'uint256' },
      { name: 'onBehalfOf', type: 'address' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'event',
    name: 'FeesCollected',
    inputs: [
      { name: 'eigenId', type: 'bytes32', indexed: true },
      { name: 'ethAmount', type: 'uint256', indexed: false },
      { name: 'tokenAmount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'FeesCompounded',
    inputs: [
      { name: 'eigenId', type: 'bytes32', indexed: true },
      { name: 'ethCompounded', type: 'uint256', indexed: false },
      { name: 'tokenCompounded', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'LiquidityRemoved',
    inputs: [
      { name: 'eigenId', type: 'bytes32', indexed: true },
      { name: 'ethAmount', type: 'uint256', indexed: false },
      { name: 'tokenAmount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'OwnerUpdated',
    inputs: [{ name: 'newOwner', type: 'address', indexed: true }],
  },
  {
    type: 'event',
    name: 'AutoCompoundUpdated',
    inputs: [
      { name: 'eigenId', type: 'bytes32', indexed: true },
      { name: 'enabled', type: 'bool', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PoolSeeded',
    inputs: [
      { name: 'eigenId', type: 'bytes32', indexed: true },
      { name: 'token', type: 'address', indexed: true },
      { name: 'poolId', type: 'bytes32', indexed: false },
      { name: 'tokenId', type: 'uint256', indexed: false },
    ],
  },
] as const;
